version: 2
jobs:
  build:
    docker:
      - image: viert/buildmachine-centos-x86_64:7
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Building XC
          command: ./build.sh
      - store_artifacts:
          path: /tmp/build/xc
